### ISSUE TITLE
Tried printing the case?

### ISSUE THREAD

**Issue by meepleek** [MrOstling/samoklava#1]
Hi, this looks great. Have you tried printing the case yet?  

Also, is the top plate required along with the PCB and case or is just the PCB + case enough?

**Comment by MrOstling** [comment]
I have printed the case. I have been using it the whole time with just the bottom and the board. I think it looks a little cleaner... at least I did. Recently I have had a couple of issues with dust/hair getting under the keys and causing issues (multiple key strikes, no key strikes, fantom key strikes, etc). I top cover does help prevent that kind of crud getting under the keys.
